[package]
name = "openvas-scanner"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }
futures = "0.3.30"
hyper = { version = "1", features = ["full"] }
hyper-rustls = "0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
serde_json = "1.0.96"
serde = { version = "1.0.163", features = ["derive"] }
uuid = { version = "1", features = ["v4", "fast-rng", "serde"] }
rustls = { version = "0.22" }
tokio-rustls = "0.25"
futures-util = "0.3.28"
rustls-pemfile = "1.0.2"
async-trait = "0.1.68"
clap = { version = "4.3.0", features = ["derive", "env"] }
toml = "0.7.4"
chacha20 = "0.9.1"
rand = "0.8.5"
pbkdf2 = { version = "0.12.2", features = ["password-hash"] }
sha2 = "0.10.7"
generic-array = "0.14.7"
base64 = "0.21.2"
hyper-util = { version = "0", features = ["tokio"] }
http-body-util = "0.1.0"
http-body = "1"
lazy_static = "1.4.0"

models = { path = "models" }
osp = { path = "osp" }
nasl-interpreter = { path = "nasl-interpreter" }
feed = { path = "feed" }
storage = { path = "storage" }
redis-storage = { path = "redis-storage" }
infisto = { path = "infisto" }
notus = { path = "notus" }
openvas = { path = "openvas" }

[workspace]
resolver = "2"
members = [
  "nasl-builtin-knowledge-base",
  "nasl-builtin-raw-ip",
  "nasl-builtin-cryptographic",
  "nasl-builtin-ssh",
  "nasl-builtin-http",
  "nasl-builtin-host",
  "nasl-builtin-string",
  "nasl-builtin-misc",
  "nasl-builtin-network",
  "nasl-builtin-description",
  "nasl-builtin-utils",
  "nasl-builtin-regex",
  "nasl-builtin-std",
  "nasl-syntax",
  "nasl-interpreter",
  "scannerctl",
  "nasl-c-lib",
  "nasl-c-lib/libgcrypt-sys",
  "storage",
  "redis-storage",
  "json-storage",
  "feed",
  "feed-verifier",
  "models",
  "osp",
  "openvas",
  "infisto",
  "smoketest",
  "notus",
  "plugin-scheduler",
  "dep-graph",
  "nasl-function-proc-macro",
]

[dev-dependencies]
tracing-test = "0.2.5"

[workspace.dependencies]
tokio = { version = "1.39.3", features = ["full"] }
futures = "0.3.30"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[[bin]]
name = "openvasd"
==== BASE ====
path = "src/openvasd/main.rs"

[[bin]]
name = "scannerctl"
path = "src/scannerctl/main.rs"
