[package]
name = "scannerlib"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.68"
base64 = "0.21.2"
chacha20 = "0.9.1"
clap = { version = "4.3.0", features = ["derive", "env"] }
configparser = "3"
crossbeam-channel = { version = "0.5.8", optional = true }
futures = "0.3.30"
futures-util = "0.3.28"
generic-array = "0.14.7"
generic-array_new = { version = "1.1", package = "generic-array" }
glob = "0.3.1"
hex = "0.4.3"
http-body = "1"
http-body-util = "0.1.0"
hyper = { version = "1", features = ["full"] }
hyper-rustls = "0"
hyper-util = { version = "0", features = ["tokio"] }
lazy-regex = "3.3.0"
lazy_static = "1.4.0"
num_cpus = "1.16.0"
pbkdf2 = { version = "0.12.2", features = ["password-hash"] }
quick-xml = { version = "0.28.1", features = ["serialize"] }
rand = "0.8.5"
rayon = { version = "1.8.0", optional = true }
redis = "0.22.3"
rustls = { version = "0.22" }
rustls-pemfile = "1.0.2"
sequoia-ipc = "0.30.1"
sequoia-openpgp = { version ="1.16.1", default-features = false, features = ["crypto-openssl"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.96"
sha2 = "0.10.7"
thiserror = "1.0.62"
tokio = { version = "1.39.3", features = ["full"] }
tokio-rustls = "0.25"
toml = "0.8.4"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "fast-rng", "serde"] }
walkdir = "2"

infisto = { path = "infisto" }
json-storage = { path = "json-storage" }
models = { path = "models" }
nasl-interpreter = { path = "nasl-interpreter" }
nasl-syntax = { path = "nasl-syntax" }
openvas = { path = "openvas" }
osp = { path = "osp" }
redis-storage = { path = "redis-storage" }
storage = { path = "storage" }

[workspace]
resolver = "2"
members = [
  "nasl-builtin-knowledge-base",
  "nasl-builtin-raw-ip",
  "nasl-builtin-cryptographic",
  "nasl-builtin-ssh",
  "nasl-builtin-http",
  "nasl-builtin-host",
  "nasl-builtin-string",
  "nasl-builtin-misc",
  "nasl-builtin-network",
  "nasl-builtin-description",
  "nasl-builtin-utils",
  "nasl-builtin-regex",
  "nasl-builtin-std",
  "nasl-syntax",
  "nasl-interpreter",
  "nasl-c-lib",
  "nasl-c-lib/libgcrypt-sys",
  "storage",
  "redis-storage",
  "json-storage",
  "models",
  "osp",
  "openvas",
  "infisto",
  "smoketest",
  "nasl-function-proc-macro",
]

[dev-dependencies]
tracing-test = "0.2.5"

[features]
dep-graph-parallel = ["rayon", "crossbeam-channel"]
default = ["dep-graph-parallel"]

[workspace.dependencies]
tokio = { version = "1.39.3", features = ["full"] }
futures = "0.3.30"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[[bin]]
name = "openvasd"
path = "src/openvasd/main.rs"

[[bin]]
name = "scannerctl"
path = "src/scannerctl/main.rs"

[[bin]]
name = "feed-verifier"
path = "src/feed_verifier/main.rs"